# Makefile du Projet: timer
#
CC   = gcc -g
LIBS = -lm

all:
	$(CC) timer1.c    -o timer1 $(LIBS)
	$(CC) timer2.c    -o timer2 $(LIBS)
	$(CC) timer3_ms.c -o timer3_ms $(LIBS)


clean:
	rm -f timer1 timer2 timer3_ms
